title: "Liu Lifu's Blog"
description: "Personal blog about technology and innovation"
author: "Liu Lifu"
url: "https://liulifu.github.io/Resume"
baseurl: "/Resume"

# Build settings
markdown: kramdown
permalink: /posts/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - .git/
  - .github/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - README.md
