name: AI Blog Enhancement
on:
  push:
    paths:
      - 'posts/**'
      - 'metadata.json'

jobs:
  enhance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers torch numpy

      - name: Process Posts
        run: python .github/scripts/process_posts.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/embeddings.json metadata.json
          git commit -m "Update AI-enhanced content" || echo "No changes to commit"
          git push
